 const Labelskey = {
    keys : [
        {  key: 'Service' },
        {  key: 'POD' },
        {  key: 'DEPLOYMENT' }, 
        {  key: 'endpoint' },
        {  key: 'instance' },
        {  key: 'metrics_path' } , 
        {  key: 'namespace' },
        {  key: 'node' },
        {  key: 'job' },
        {  key: 'mutatingwebhookconfiguration' },
        {  key: 'resource' },
        {  key: 'kind' }, 
        {  key: 'version' },
        {  key: 'le' },
        {  key: 'severity' } , 
        {  key: 'status ' },
        {  key: 'cpu' },
        {  key: 'code' },
        {  key: 'component' },
        {  key: 'contentType' },
        {  key: 'scope' }, 
        {  key: 'verb' },
        {  key: 'memory' },
        {  key: 'alertstate' },
        {  key: 'alertname' }, 
        {  key: 'apiservice' },
        {  key: 'reason' },
        {  key: 'name' } , 
        {  key: 'operation' },
        {  key: 'rejected' },
        {  key: 'type' },
        {  key: 'quantile' },
        {  key: 'group' },
        {  key: 'username' }, 
        {  key: 'container' },
        {key: 'id' },
        {  key: 'image ' },
        {  key: 'kubernetes_io_hostname' },
        {  key: 'kubernetes_io_os' },
        {  key: 'dockerVersion' },
        {  key: 'kernelVersion' },
        {  key: 'k8s_app' }, 
        {  key: 'server' },
        {  key: 'zone' },
        {  key: 'kubernetes_name' },
        {  key: 'beta_kubernetes_io_arch' }, 
        {  key: 'grpc_method' },
        {  key: 'grpc_type' },
        {  key: 'grpc_service' } , 
        {  key: 'configmap' },
        {  key: 'resource_version' },
        {  key: 'daemonset' },
        {  key: 'label_k8s_app' },
        {  key: 'deployment' },
        {  key: 'label_app' }, 
        {  key: 'container_id' },
        {key: 'image_id' },
        {  key: 'owner_kind ' },
        {  key: 'owner_name' },
        {  key: 'replicaset' },
        {  key: 'owner_is_controller' },
        {  key: 'secret' },
        {  key: 'storageclass' }, 
        {  key: 'uid' },
        {  key: 'operation_type' },
        {  key: 'minikube_k8s_io_version' },
        {  key: 'server_type' }, 
        {  key: 'grpc_method' },
        {  key: 'grpc_type' },
        {  key: 'grpc_service' } , 
        {  key: 'configmap' },
        {  key: 'resource_version' },
        {  key: 'daemonset' },
        {  key: 'label_k8s_app' },
        {  key: 'deployment' },
        {  key: 'label_app' }, 
        {  key: 'container_id' },
        {key: 'image_id' },
            
    ]
}
export default Labelskey;